# Generated by Django 4.1 on 2024-02-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simuser',
            name='balance',
            field=models.DecimalField(decimal_places=10, default=100000, max_digits=20),
        ),
    ]
