# Generated by Django 4.2.6 on 2024-02-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_orders_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
