# Generated by Django 4.2.6 on 2024-02-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_orders_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='profit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
