# Generated by Django 4.2.6 on 2024-02-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0008_forums'),
    ]

    operations = [
        migrations.AddField(
            model_name='forums',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
