# Generated by Django 4.2.6 on 2024-03-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0010_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuser',
            name='app_points',
            field=models.IntegerField(default=0),
        ),
    ]
