# Generated by Django 4.2.6 on 2024-03-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0012_posts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='users_liked_array_field',
            field=models.TextField(default='[]'),
        ),
    ]
