# Generated by Django 4.2.6 on 2024-03-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0014_posts_users_disliked_array_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuser',
            name='level',
            field=models.CharField(default='Newbie', max_length=255),
        ),
    ]
