# Generated by Django 4.2.6 on 2024-03-19 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0016_alter_simuser_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simuser',
            name='level',
        ),
    ]
