# Generated by Django 4.2.6 on 2024-04-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0018_simuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='broker.posts'),
        ),
    ]
