# Generated by Django 4.2.6 on 2024-04-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0019_posts_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='simuser',
            name='profit',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
