# Generated by Django 4.2.6 on 2024-04-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0023_orders_user_total_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=20),
        ),
    ]
