# Generated by Django 4.2.6 on 2024-04-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0024_alter_simuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='trade_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='simuser',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
