# Generated by Django 5.0.1 on 2024-01-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='simuser',
            managers=[
            ],
        ),
    ]
