# Generated by Django 4.2.6 on 2024-04-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0020_simuser_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simuser',
            name='profit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
