# Generated by Django 4.2.6 on 2024-04-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0021_alter_simuser_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='profit',
            new_name='trade_profit',
        ),
    ]
