# Generated by Django 4.2.6 on 2024-04-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0022_rename_profit_orders_trade_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_total_profit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
    ]
